language: go
go: 
 - 1.1
 - 1.2
 - release
 - tip

install:
 - export PATH=$PATH:$HOME/gopath/bin
 - go get github.com/smartystreets/goconvey
 - go get github.com/garyburd/redigo
 - go get github.com/nu7hatch/gouuid

script:
 - go test -v ./...
